# -*- coding: utf-8 -*-
# @Author: Wenwen Yu
# @Created Time: 7/8/2020 9:34 PM

Entities_list = [
        "key_company_name",
        "key_company_address",
        "key_company_tel",
        "key_company_fax",
        "key_bank_name",
        "key_branch_name",
        "key_account_name",
        "key_account_type",
        "key_account_number",
        "key_amount_excluding_tax",
        "key_amount_including_tax",
        "key_item_name",
        "key_item_quantity",
        "key_item_unit",
        "key_item_unit_amount",
        "key_item_total_amount",
        "key_tax",
        "key_company_zipcode",
        "key_payment_date",
        "key_issued_date",
        "key_delivery_date",
        "key_document_number",
        "key_invoice_number",
        "key_item_line_number",
        "key_company_department_name",
        "value_company_name",
        "value_company_address",
        "value_company_tel",
        "value_company_fax",
        "value_bank_name",
        "value_branch_name",
        "value_account_name",
        "value_account_type",
        "value_account_number",
        "value_amount_excluding_tax",
        "value_amount_including_tax",
        "value_item_name",
        "value_item_quantity",
        "value_item_unit",
        "value_item_unit_amount",
        "value_item_total_amount",
        "value_tax",
        "value_company_zipcode",
        "value_payment_date",
        "value_issued_date",
        "value_delivery_date",
        "value_document_number",
        "value_invoice_number",
        "value_item_line_number",
        "value_company_department_name"
      ]

# Entities_list = [
#     "ticket_num",
#     "starting_station",
#     "train_num",
#     "destination_station",
#     "date",
#     "ticket_rates",
#     "seat_category",
#     "name"
# ]